= Red Hat OpenShift Dev Spaces Administration
:navtitle: Home

== Introduction

Welcome to this quick course on the _Red Hat OpenShift Dev Spaces Administration_.
This course is the `second` in a series of `five` courses about Red Hat OpenShift DevSpaces:

. https://redhatquickcourses.github.io/devspaces-intro[Introduction to Red Hat OpenShift Dev Spaces^]
. Red Hat OpenShift Dev Spaces Administration (_This course_)
. https://redhatquickcourses.github.io/devspaces-security[Securing Access to Red Hat OpenShift Dev Spaces^]
. https://redhatquickcourses.github.io/devspaces-workspaces[Creating and Customizing Workspaces in Red Hat OpenShift DevSpaces^]
. https://redhatquickcourses.github.io/devspaces-plugins[Configuring Plugins in Red Hat OpenShift Dev Spaces^]

This course covers the install, updates, and uninstall process for Red Hat OpenShift Dev Spaces.

NOTE: The hands-on labs for this course have been tested on *Red Hat OpenShift Dev Spaces 3.16*. The labs should mostly work on minor update releases of Dev Spaces. If you encounter any issues, please open a GitHub issue in the course repository.

== Course Objectives

The overall objectives of this course include:

* Install, Upgrade, and Uninstall Red Hat OpenShift Dev Spaces on the OpenShift Container Platform
** Using the operator
** Using the `oc` and `dsc` CLIs
** Using Red Hat OpenShift GitOps
* Basic configuration of Dev Spaces server components
* Configure container image caching to speed up Dev Spaces workspaces start up
* Configure the `fuse-overlayfs` storage driver to improve performance of container builds
* Manage workspaces using the `oc` CLI
* Configure workspace storage strategy

== Course Prerequisites

* Basic knowledge of OpenShift (or Kubernetes) administration
* Knowledge of building Docker or Podman containers
* Deploying container images on OpenShift or Kubernetes
* OpenShift or Kubernetes User and Role Administration (RBAC)

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Rutuja Deshmukh
* Anna Swicegood
* Anton Giertli
* Anatolii Bazko

== Classroom Environment

=== For Red Hat Associates

Red Hat associates and others who have access to the Red Hat Demo Platform (RHDP) should use the https://demo.redhat.com/catalog?item=babylon-catalog-prod/sandboxes-gpte.sandbox-ocp.prod[AWS with OpenShift Open Environment^] catalog item.

This classroom does *NOT* have Dev Spaces pre-installed. You install and configure a basic Dev Spaces instance in this course, and then continue using this instance with other courses in the learning path.

Click the RHDP link above, log in to RHDP, and click `Order` to request a new OpenShift cluster. On the order page for the catalog item, do the following:

* *Activity*: Select `Practice/Enablement`
* *Purpose*: Select `Learning about the Product`
* *Salesforce ID*: If you have an opportunity ID, enter it into this field, otherwise select `Project`, and then enter "Learning about Dev Spaces" in the text field. You will see a warning message that a Salesforce ID is required, but you can safely ignore it.
* *Features*: Select `Enable Let's Encrypt`
* *Region*: Select the AWS region closest to your location
* *User count*: `1`
* *Control Plane Count*: `1`
* *OpenShift Version*: `4.16` or higher
* *Control Plane Instance Type*: `m6a.4xlarge`

Select the checkbox at the bottom of the page to confirm that lab costs will be charged to your cost center, and click `Order`.

NOTE: The lab environment will take an hour to provision. You can check the status and details of the OpenShift cluster from the `Services` page of RHDP. The classroom is available for 48 hours initially. You can extend the duration of classroom availability by clicking `Help > Get Technical Help` in RHDP, and then requesting an extension by opening a ServiceNow ticket with the RHDP team.

=== For Red Hat Partners

Red Hat partners and others who do not have access to RHDP, should provision their own Red Hat OpenShift 4.16+ cluster using the Red Hat Hybrid Cloud Console at https://console.redhat.com/openshift/overview[window=_blank]. Ensure that you provision an OpenShift 4.16 cluster with at least 16 vCPUs and 64GB of RAM.

NOTE: You can also install Dev Spaces and run the hands-on labs using OpenShift Local, provided you allocate a minimum of 16 vCPUs and 32GB+ RAM. Go to https://developers.redhat.com/products/openshift-local/overview[window=_blank] and click on `Install OpenShift on your laptop`.
